apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-repo-git
  namespace: argocd
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: argocd-repo-git
    creationPolicy: Owner
    template:
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repository
  data:
    - secretKey: url
      remoteRef:
        key: argocd/github
        property: url
    - secretKey: username
      remoteRef:
        key: argocd/github
        property: username
    - secretKey: password
      remoteRef:
        key: argocd/github
        property: token
