Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-22.04"
#   config.vm.box = "hashicorp-education/ubuntu-24-04"
  config.vm.box_version = "202510.26.0"

  config.vm.provider "virtualbox" do |vb|
    vb.name   = "prod-sim"
    vb.memory = 4096
    vb.cpus   = 2
  end

  config.vm.network "private_network", ip: "192.168.56.20"
  config.vm.network "forwarded_port", guest: 8080, host: 8080
  # Run the external provisioning script
  config.vm.provision "shell", path: "provision.sh"
end
